### ISSUE TITLE
Upload MP4 Video via Twitter Media API

### ISSUE THREAD

**Issue by pannpers** [pannpers/hitorec#34]
# Overview
[Chunked media upload — Twitter Developers](https://developer.twitter.com/en/docs/media/upload-media/uploading-media/chunked-media-upload) の手順に従い、Twitter API経由でMP4動画ファイルをアップロードできるようにする。

# To-Do

- [x] Cloud FunctionsのStorage Triggerを使用し、音声Uploadが完了したら、MP4 (H264 codec and AAC audio) にフォーマット変換を行う。
- [x] MP4をTwitter API経由でアップロードする。
- [ ] Cloud FunctionsからTwitter APIのAuthenticationを行うために、JWTからAccess Tokenを取得する。

# Notes
References
- [Uploading media — Twitter Developers](https://developer.twitter.com/en/docs/tutorials/uploading-media#chunked-upload)
- [Media best practices — Twitter Developers](https://developer.twitter.com/en/docs/media/upload-media/uploading-media/media-best-practices)
- [The Best Twitter Video Format You Should Be Using](https://blog.snappa.com/twitter-video-format/)
> Specifically, you’ll need to have an MP4 video format that has H264 codec (which is the quality of compression and decompression and can significantly impact the quality of the uploaded video), and AAC audio. The H264 codec and AAC audio is standard for many MP4 videos.

- [Cloud Pub/Sub Notifications for Cloud Storage  \|  Google Cloud](https://cloud.google.com/storage/docs/pubsub-notifications?hl=ja)
- [オブジェクト変更の登録  \|  Cloud Storage  \|  Google Cloud](https://cloud.google.com/storage/docs/reporting-changes?hl=ja#listing)

- [Triggering from Pub/Sub push  \|  Cloud Run  \|  Google Cloud](https://cloud.google.com/run/docs/triggering/pubsub-push#run_pubsub_handler-go)
- [Using Pub/Sub with Cloud Run tutorial  \|  Cloud Run Documentation](https://cloud.google.com/run/docs/tutorials/pubsub#run_pubsub_server-go)

```sh
$ gsutil notification list gs://hitorec-app.appspot.com

$ gsutil notification create -t audio-uploaded -e OBJECT_FINALIZE -f json gs://hitorec-app.appspot.com
$ gsutil notification list gs://hitorec-app.appspot.com

$ gcloud projects add-iam-policy-binding hitorec-app --member=serviceAccount:service-297414771339@gcp-sa-pubsub.iam.gserviceaccount.com --role=roles/iam.serviceAccountTokenCreator

$ gcloud run services add-iam-policy-binding media-converter --member=serviceAccount:media-converter@hitorec-app.iam.gserviceaccount.com --role=roles/run.invoker

$ gcloud pubsub subscriptions create convert-audio \
    --topic audio-uploaded \
    --push-endpoint=https://media-converter-tgridmk4ha-an.a.run.app \
    --push-auth-service-account=media-converter@hitorec-app.iam.gserviceaccount.com
```

**Comment by pannpers** [comment]
## GCP Resources

- PubSub
  - Topic: [audio-uploaded](https://console.cloud.google.com/cloudpubsub/topic/detail/audio-uploaded?project=hitorec-app&authuser=0)
  - Subscription: [convert-audio](https://console.cloud.google.com/cloudpubsub/subscription/detail/convert-audio?authuser=0&project=hitorec-app)
- IAM
  - ServiceAccount: [media-converter](https://console.cloud.google.com/iam-admin/serviceaccounts/details/112921430766130407934?authuser=0&project=hitorec-app)
- Cloud Run
  - [media-converter](https://console.cloud.google.com/run/detail/asia-northeast1/media-converter/revisions?project=hitorec-app)
