### ISSUE TITLE
Change Domain from hitocoto to hitorec

### ISSUE THREAD

**Issue by pannpers** [pannpers/hitorec#37]
# Overview
サービス名を `hitocoto` から `hitorec` に変更したため、プロジェクト名やアカウントなど、もろもろの変更を行う。

# To-Do

- [x] Google Domains で `hitorec.app` を購入
- [x] Google Account で `hitorec@gmail.com` を登録
- [x] Twitter で `hitorec_app` ユーザーを登録 (`hitorec` は既に存在していたため)
- [x] Twitter Developer コンソールでアプリ登録を行う
- [x] Firebaseで `hitorec` プロジェクトを作成する 

# Notes
